name: chat
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src
    working_dir: /app
    # Added custom command to fix issue with nodemon not working correctly on windows under Docker
    command: npx nodemon --legacy-watch src/index.ts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - 80:5173
    volumes:
      - ./frontend/src:/app/src
    working_dir: /app
