name: chat
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /app
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - 80:5173
    working_dir: /app
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
