name: chat
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - 80:5173
    volumes:
      - ./frontend/src:/app/src
    working_dir: /app
